var data = {
        wyy:{
            name:'仿网易云音乐桌面音乐播放器',
            author:'张晓辉',
            dec:'这款应用基于桌面跨平台框架electron进行开发，开发时使用react，redux，react-router全家桶框架进行开发，可以支持在Windows，linux，mac三大操作系统上面安装运行。本项目由github著名项目NeteaseCloudMusicApi提供后台服务，使用的后台语言为nodejs，可以使用该软件直接登陆用户的网易云音乐账号进行使用。基本模块涵盖有：登录注册、绑定/换绑手机网易云音乐账号，访问用户信息，用户歌单。支持播放本地音乐和在线音乐，播放在线mv，查看歌手，歌曲榜单，mv，专辑，电台，以及上述所有资源的评论，点赞，平台资源模糊搜索等等.',
            github:'https://github.com/WTAufPzIv/neteasymusic',
            download:null,
            img:[
                'wyy_0.png',
                'wyy_1.png',
                'wyy_2.png',
                'wyy_3.png',
            ],
            plat:'windows'
        },
        rck:{
            name:'日程块',
            author:'吴家俊',
            dec:'基于Android的多功能日程管理软件是一款为学生开发的日程管理APP，用户通过使用该APP，可以使用制定本周日程、添加倒计时、进入禁玩手机模式，分享本周日程、查看天气提示等一系列功能，为用户的生活添加便利,软件Android Studio设计应用界面，使用Android手机自带的SQLite数据库管理系统，本地实现数据的存取，方便高效。',
            github:null,
            download:null,
            plat:'phone',
            img:[
                'rck_1.jpg',
                'rck_2.jpg',
                'rck_3.jpg',
                'rck_4.jpg',
            ]
        },
        wt:{
            name:'wetalk',
            author:'吴仔健',
            dec:'wetalk是一个促成行业一般从业者与专家之间，企业与专家之间，企业与企业之间的交流与合作的平台。它将传统的线下技术对接的一部分或大部分工作转 移到线上，打破传统技术对接在时间和空间上的屏障，做到更快，更高效的交流。',
            github:null,
            download:'https://www.lanzous.com/i4e31he',
            plat:'phone',
            img:[
                'wt_1.png',
                'wt_2.png',
                'wt_3.png',
                'wt_4.png',
            ]
        },
        qxp:{
            name:'一身诗意千寻铺',
            author:'张晓辉,吴家俊',
            dec:'在互联网时代，如今的“失物招领/寻物启事”早已不是传统时候人们在大街公告栏、电线杆或墙壁上所粘贴的纸质公告，但在校园内，丢失和捡到东西的情况依然十分普遍，使得“失物招领/寻物启事”这一概念将一直存在于校园之中，而在快节奏生活的背景之下，学生在丢失或捡到东西后只希望能快速找到自己丢失的东西或失主，不过多浪费自己的时间和精力，这是传统纸质公告和校园广播等等方式所不可能实现的，为了满足上述需求，我们开发了这款小程序，集成了上述业务需求，旨在方便广大高校学子。“失物招领/寻物启事”公告栏：查看自己学校当前所有的启示，启示列表按照发布的时间排序，同时启示根据生活常用物品进行了分类：钥匙、卡、包类、杯子、电子产品、书本、雨伞、文具、生活用品、证件、衣物、其他这12种分类，用户可以选择查看全部告示，也可以查看某一分类下的告示，用户点击告示列表可以查看所点击的告示详情，以及联系线索提供人。“搜索”：用户可以通过关键字对所有告示进行模糊搜索，快速定位所要找的东西，同时还具有搜索历史记录的功能。“管理告示”：对于发布告示的用户，可以选择重新编辑告示，也可以选择关闭（删除）自己发布的告示。“发布告示”：用户可以快速编辑一条告示发布到告示栏中，只需要提供一些基础信息：物品名称，时间，地点，联系方式，除了这些之外还可以选填补充信息和上传图片',
            github:'https://github.com/WTAufPzIv/lost_and_found',
            download:null,
            plat:'phone',
            img:[
                'qxp_1.png',
                'qxp_2.png',
                'qxp_3.png',
                'qxp_4.png',
            ]
        },
        am:{
            name:'AppMarket',
            author:'吴仔健',
            dec:'模仿华为应用市场的一款手机app',
            github:null,
            download:null,
            plat:'phone',
            img:[
                'AppMarket_1.jpeg',
                'AppMarket_2.jpeg',
                'AppMarket_3.jpeg',
                'AppMarket_4.jpeg',
            ]
        },
        ep:{
            name:'EventParticipant',
            author:'吴仔健',
            dec:'一款能够发布活动以及物物交换的app',
            github:null,
            download:null,
            plat:'phone',
            img:[
                'EventParticipant_1.jpg',
                'EventParticipant_2.jpg',
                'EventParticipant_3.jpg',
            ]
        },
        kdxd:{
            name:'科大小店',
            author:'许志凡',
            dec:'这是一款校内跳蚤市场的软件，这款软件可以进行二手商品等物品发布与购买，还可以发布活动和报名参加活动。主要是提供一个商品与活动的展示平台。具体的购买和活动报名需要线下进行。',
            github:null,
            download:null,
            plat:'phone',
            img:[
                '科大小店_1.jpg',
                '科大小店_2.jpg',
                '科大小店_3.jpg',
                '科大小店_4.jpg',
            ]
        },
        xlkdb:{
            name:'心理课代表',
            author:'田文彪',
            dec:'一款针对大学生的关于心理问题咨询的app，会有一些非专业的同为大学生的心理课代表(心理辅导员)在线帮助他们进行调解，以及一个群体至今互相交流，互相帮助',
            github:null,
            download:null,
            plat:'phone',
            img:[
                '心理课代表_1.jpg',
                '心理课代表_2.jpg',
                '心理课代表_3.jpg',
            ]
        }
    }
export default data